export interface ISpecComponents {
    ComponentID: number;
    ComponentType: string;
    CategoryID: string;
    Name: string;
    AbbrName: string;
    NotReqXML: number;
    Description?: string;
    updated?: string;
    updatedEP?: number;
    added: string;
    addedEP?: number;
}

export const COMPONENTS: ISpecComponents[] = [
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The CommissionDate component block is used to carry commission information such as the type of commission and the rate.',
        added: 'FIX.4.3',
        AbbrName: 'Comm',
        NotReqXML: 0,
        ComponentID: 1000,
        Name: 'CommissionData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The presence of DiscretionInstructions component block on an order indicates that the trader wishes to display one price but will accept trades at another price.',
        added: 'FIX.4.4',
        AbbrName: 'DiscInstr',
        NotReqXML: 0,
        ComponentID: 1001,
        Name: 'DiscretionInstructions',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'Component block is optionally used only for financing deals to identify the legal agreement under which the deal was made and other unique characteristics of the transaction. The AgreementDesc field refers to base standard documents such as MRA 1996 Repurchase Agreement, GMRA 2000 Bills Transaction (U.K.), MSLA 1993 Securities Loan – Amended 1998, for example.',
        added: 'FIX.4.4',
        AbbrName: 'FinDetls',
        NotReqXML: 0,
        ComponentID: 1002,
        Name: 'FinancingDetails',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The Instrument component block contains all the fields commonly used to describe a security or instrument. Typically the data elements in this component block are considered the static data of a security, data that may be commonly found in a security master database. The Instrument component block can be used to describe any asset type supported by FIX.',
        added: 'FIX.4.3',
        AbbrName: 'Instrmt',
        NotReqXML: 0,
        ComponentID: 1003,
        Name: 'Instrument',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The InstrumentExtension component block identifies additional security attributes that are more commonly found for Fixed Income securities.',
        added: 'FIX.4.4',
        AbbrName: 'InstrmtExt',
        NotReqXML: 0,
        ComponentID: 1004,
        Name: 'InstrumentExtension',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The InstrumentLeg component block, like the Instrument component block, contains all the fields commonly used to describe a security or instrument. In the case of the InstrumentLeg component block it describes a security used in multileg-oriented messages.',
        added: 'FIX.4.3',
        AbbrName: 'Leg',
        NotReqXML: 0,
        ComponentID: 1005,
        Name: 'InstrumentLeg',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The LegBenchmarkCurveData is used to convey the benchmark information used for pricing in a multi-legged Fixed Income security.',
        added: 'FIX.4.4',
        AbbrName: 'BnchmkCurve',
        NotReqXML: 0,
        ComponentID: 1006,
        Name: 'LegBenchmarkCurveData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The LegStipulations component block has the same usage as the Stipulations component block, but for a leg instrument in a multi-legged security.',
        added: 'FIX.4.4',
        AbbrName: 'Stip',
        NotReqXML: 0,
        ComponentID: 1007,
        Name: 'LegStipulations',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The NestedParties component block is identical to the Parties Block. It is used in other component blocks and repeating groups when nesting will take place resulting in multiple occurrences of the Parties block within a single FIX message.. Use of NestedParties under these conditions avoids multiple references to the Parties block within the same message which is not allowed in FIX tag/value syntax.',
        added: 'FIX.4.3',
        AbbrName: 'Pty',
        NotReqXML: 0,
        ComponentID: 1008,
        Name: 'NestedParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The OrderQtyData component block contains the fields commonly used for indicating the amount or quantity of an order. Note that when this component block is marked as "required" in a message either one of these three fields must be used to identify the amount: OrderQty, CashOrderQty or OrderPercent (in the case of CIV).',
        added: 'FIX.4.3',
        AbbrName: 'OrdQty',
        NotReqXML: 0,
        ComponentID: 1011,
        Name: 'OrderQtyData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The Parties component block is used to identify and convey information on the entities both central and peripheral to the financial transaction represented by the FIX message containing the Parties Block. The Parties block allows many different types of entites to be expressed through use of the PartyRole field and identifies the source of the PartyID through the the PartyIDSource.',
        added: 'FIX.4.3',
        AbbrName: 'Pty',
        NotReqXML: 0,
        ComponentID: 1012,
        Name: 'Parties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The Peg Instructions component block is used to tie the price of a security to a market event such as opening price, mid-price, best price. The Peg Instructions block may also be used to tie the price to the behavior of a related security.',
        added: 'FIX.4.4',
        AbbrName: 'PegInstr',
        NotReqXML: 0,
        ComponentID: 1013,
        Name: 'PegInstructions',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The PositionAmountData component block is used to report netted amounts associated with position quantities. In the listed derivatives market the amount is generally expressing a type of futures variation or option premium. In the equities market this may be the net pay or collect on a given position.',
        added: 'FIX.4.4',
        AbbrName: 'Amt',
        NotReqXML: 0,
        ComponentID: 1014,
        Name: 'PositionAmountData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The PositionQty component block specifies the various types of position quantity in the position life-cycle including start-of-day, intraday, trade, adjustments, and end-of-day position quantities. Quantities are expressed in terms of long and short quantities.',
        added: 'FIX.4.4',
        AbbrName: 'Qty',
        NotReqXML: 0,
        ComponentID: 1015,
        Name: 'PositionQty',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The SettlInstructionsData component block is used to convey key information regarding standing settlement and delivery instructions. It also provides a reference to standing settlement details regarding the source, delivery instructions, and settlement parties',
        added: 'FIX.4.4',
        AbbrName: 'SetInstr',
        NotReqXML: 0,
        ComponentID: 1016,
        Name: 'SettlInstructionsData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The SettlParties component block is used in a similar manner as Parties Block within the context of settlement instruction messages to distinguish between parties involved in the settlement and parties who are expected to execute the settlement process.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        NotReqXML: 0,
        ComponentID: 1017,
        Name: 'SettlParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The SpreadOrBenchmarkCurveData component block is primarily used for Fixed Income to convey spread to a benchmark security or curve.',
        added: 'FIX.4.3',
        AbbrName: 'SprdBnchmkCurve',
        NotReqXML: 0,
        ComponentID: 1018,
        Name: 'SpreadOrBenchmarkCurveData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The Stipulations component block is used in Fixed Income to provide additional information on a given security. These additional information are usually not considered static data information.',
        added: 'FIX.4.3',
        AbbrName: 'Stip',
        NotReqXML: 0,
        ComponentID: 1019,
        Name: 'Stipulations',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The TrdRegTimestamps component block is used to express timestamps for an order or trade that are required by regulatory agencies These timesteamps are used to identify the timeframes for when an order or trade is received on the floor, received and executed by the broker, etc.',
        added: 'FIX.4.4',
        AbbrName: 'TrdRegTS',
        NotReqXML: 0,
        ComponentID: 1020,
        Name: 'TrdRegTimestamps',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The UnderlyingInstrument component block, like the Instrument component block, contains all the fields commonly used to describe a security or instrument. In the case of the UnderlyingInstrument component block it describes an instrument which underlies the primary instrument Refer to the Instrument component block comments as this component block mirrors Instrument, except for the noted fields.',
        added: 'FIX.4.3',
        AbbrName: 'Undly',
        NotReqXML: 0,
        ComponentID: 1021,
        Name: 'UnderlyingInstrument',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description: 'The YieldData component block conveys yield information for a given Fixed Income security.',
        added: 'FIX.4.3',
        AbbrName: 'Yield',
        NotReqXML: 0,
        ComponentID: 1022,
        Name: 'YieldData',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The UnderlyingStipulations component block has the same usage as the Stipulations component block, but for an underlying security.',
        added: 'FIX.4.4',
        AbbrName: 'Stip',
        NotReqXML: 0,
        ComponentID: 1023,
        Name: 'UnderlyingStipulations',
    },
    {
        CategoryID: 'Session',
        ComponentType: 'Block',
        Description: 'The standard FIX message header',
        added: 'FIX.4.0',
        AbbrName: 'BaseHeader',
        NotReqXML: 0,
        ComponentID: 1024,
        Name: 'StandardHeader',
    },
    {
        CategoryID: 'Session',
        ComponentType: 'Block',
        Description: 'The standard FIX message trailer',
        added: 'FIX.4.0',
        AbbrName: 'Trlr',
        NotReqXML: 1,
        ComponentID: 1025,
        Name: 'StandardTrailer',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The NestedParties2 component block is identical to the Parties Block. It is used in other component blocks and repeating groups when nesting will take place resulting in multiple occurrences of the Parties block within a single FIX message.. Use of NestedParties2 under these conditions avoids multiple references to the Parties block within the same message which is not allowed in FIX tag/value syntax.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        NotReqXML: 0,
        ComponentID: 1009,
        Name: 'NestedParties2',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The NestedParties3 component block is identical to the Parties Block. It is used in other component blocks and repeating groups when nesting will take place resulting in multiple occurrences of the Parties block within a single FIX message.. Use of NestedParties3 under these conditions avoids multiple references to the Parties block within the same message which is not allowed in FIX tag/value syntax.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        NotReqXML: 0,
        ComponentID: 1010,
        Name: 'NestedParties3',
    },
    {
        CategoryID: 'OrderMassHandling',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'AffectOrd',
        NotReqXML: 0,
        ComponentID: 2001,
        Name: 'AffectedOrdGrp',
    },
    {
        CategoryID: 'Allocation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'AllocAck',
        NotReqXML: 0,
        ComponentID: 2002,
        Name: 'AllocAckGrp',
    },
    {
        CategoryID: 'Allocation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Alloc',
        NotReqXML: 0,
        ComponentID: 2003,
        Name: 'AllocGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'CompReq',
        NotReqXML: 0,
        ComponentID: 2004,
        Name: 'BidCompReqGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'CompRsp',
        NotReqXML: 0,
        ComponentID: 2005,
        Name: 'BidCompRspGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'DescReq',
        NotReqXML: 0,
        ComponentID: 2006,
        Name: 'BidDescReqGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'ClrInst',
        NotReqXML: 0,
        ComponentID: 2007,
        Name: 'ClrInstGrp',
    },
    {
        CategoryID: 'CollateralManagement',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Qual',
        NotReqXML: 0,
        ComponentID: 2008,
        Name: 'CollInqQualGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'CIDReq',
        NotReqXML: 0,
        ComponentID: 2009,
        Name: 'CompIDReqGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'CIDStat',
        NotReqXML: 0,
        ComponentID: 2010,
        Name: 'CompIDStatGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'ContAmt',
        NotReqXML: 0,
        ComponentID: 2011,
        Name: 'ContAmtGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Contra',
        NotReqXML: 0,
        ComponentID: 2012,
        Name: 'ContraGrp',
    },
    {
        CategoryID: 'Confirmation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'Cpcty',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2013,
        Name: 'CpctyConfGrp',
    },
    {
        CategoryID: 'Allocation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'AllExc',
        NotReqXML: 0,
        ComponentID: 2014,
        Name: 'ExecAllocGrp',
    },
    {
        CategoryID: 'CollateralManagement',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'CollExc',
        NotReqXML: 0,
        ComponentID: 2015,
        Name: 'ExecCollGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Inst',
        NotReqXML: 0,
        ComponentID: 2017,
        Name: 'InstrmtGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Exec',
        NotReqXML: 0,
        ComponentID: 2018,
        Name: 'InstrmtLegExecGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'OptimisedImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 76,
        AbbrName: 'Leg',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2019,
        Name: 'InstrmtLegGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'IOI',
        NotReqXML: 0,
        ComponentID: 2020,
        Name: 'InstrmtLegIOIGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'SecL',
        NotReqXML: 0,
        ComponentID: 2021,
        Name: 'InstrmtLegSecListGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'InstReq',
        NotReqXML: 0,
        ComponentID: 2022,
        Name: 'InstrmtMDReqGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'StrkPX',
        NotReqXML: 0,
        ComponentID: 2023,
        Name: 'InstrmtStrkPxGrp',
    },
    {
        CategoryID: 'Indication',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Qual',
        NotReqXML: 0,
        ComponentID: 2024,
        Name: 'IOIQualGrp',
    },
    {
        CategoryID: 'MultilegOrders',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Ord',
        NotReqXML: 0,
        ComponentID: 2025,
        Name: 'LegOrdGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'PreAll',
        NotReqXML: 0,
        ComponentID: 2026,
        Name: 'LegPreAllocGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Quot',
        NotReqXML: 0,
        ComponentID: 2027,
        Name: 'LegQuotGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuoteStat',
        NotReqXML: 0,
        ComponentID: 2028,
        Name: 'LegQuotStatGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'TxtLn',
        NotReqXML: 0,
        ComponentID: 2029,
        Name: 'LinesOfTextGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Ord',
        NotReqXML: 0,
        ComponentID: 2030,
        Name: 'ListOrdGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Full',
        NotReqXML: 0,
        ComponentID: 2031,
        Name: 'MDFullGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Inc',
        NotReqXML: 0,
        ComponentID: 2032,
        Name: 'MDIncGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Req',
        NotReqXML: 0,
        ComponentID: 2033,
        Name: 'MDReqGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Rjct',
        NotReqXML: 0,
        ComponentID: 2034,
        Name: 'MDRjctGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'MiscFees',
        NotReqXML: 0,
        ComponentID: 2035,
        Name: 'MiscFeesGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'OrdAlloc',
        NotReqXML: 0,
        ComponentID: 2036,
        Name: 'OrdAllocGrp',
    },
    {
        CategoryID: 'ProgramTrading',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'ListStat',
        NotReqXML: 0,
        ComponentID: 2037,
        Name: 'OrdListStatGrp',
    },
    {
        CategoryID: 'PositionMaintenance',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'PosUnd',
        NotReqXML: 0,
        ComponentID: 2038,
        Name: 'PosUndInstrmtGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'PreAll',
        NotReqXML: 0,
        ComponentID: 2039,
        Name: 'PreAllocGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'PreAllocMleg',
        NotReqXML: 0,
        ComponentID: 2040,
        Name: 'PreAllocMlegGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotCxlEntry',
        NotReqXML: 0,
        ComponentID: 2041,
        Name: 'QuotCxlEntriesGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotEntryAck',
        NotReqXML: 0,
        ComponentID: 2042,
        Name: 'QuotEntryAckGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotEntry',
        NotReqXML: 0,
        ComponentID: 2043,
        Name: 'QuotEntryGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotQual',
        NotReqXML: 0,
        ComponentID: 2044,
        Name: 'QuotQualGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotReq',
        NotReqXML: 0,
        ComponentID: 2045,
        Name: 'QuotReqGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Leg',
        NotReqXML: 0,
        ComponentID: 2046,
        Name: 'QuotReqLegsGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotReqRej',
        NotReqXML: 0,
        ComponentID: 2047,
        Name: 'QuotReqRjctGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotSetAck',
        NotReqXML: 0,
        ComponentID: 2048,
        Name: 'QuotSetAckGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'QuotSet',
        NotReqXML: 0,
        ComponentID: 2049,
        Name: 'QuotSetGrp',
    },
    {
        CategoryID: 'SecuritiesReferenceData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'RelSym',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2050,
        Name: 'RelSymDerivSecGrp',
    },
    {
        CategoryID: 'QuotationNegotiation',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'RFQReq',
        NotReqXML: 0,
        ComponentID: 2051,
        Name: 'RFQReqGrp',
    },
    {
        CategoryID: 'RegistrationInstruction',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'RgDtlInst',
        NotReqXML: 0,
        ComponentID: 2052,
        Name: 'RgstDistInstGrp',
    },
    {
        CategoryID: 'RegistrationInstruction',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'RgDtl',
        NotReqXML: 0,
        ComponentID: 2053,
        Name: 'RgstDtlsGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Rtg',
        NotReqXML: 0,
        ComponentID: 2054,
        Name: 'RoutingGrp',
    },
    {
        CategoryID: 'SecuritiesReferenceData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'SecL',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2055,
        Name: 'SecListGrp',
    },
    {
        CategoryID: 'SecuritiesReferenceData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'SecT',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2056,
        Name: 'SecTypesGrp',
    },
    {
        CategoryID: 'SettlementInstruction',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'SetInst',
        NotReqXML: 0,
        ComponentID: 2057,
        Name: 'SettlInstGrp',
    },
    {
        CategoryID: 'CrossOrders',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'SideCrossCxl',
        NotReqXML: 0,
        ComponentID: 2058,
        Name: 'SideCrossOrdCxlGrp',
    },
    {
        CategoryID: 'CrossOrders',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'SideCrossMod',
        NotReqXML: 0,
        ComponentID: 2059,
        Name: 'SideCrossOrdModGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'Alloc',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2060,
        Name: 'TrdAllocGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'RptSide',
        NotReqXML: 0,
        ComponentID: 2061,
        Name: 'TrdCapRptSideGrp',
    },
    {
        CategoryID: 'CollateralManagement',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'TrdColl',
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2062,
        Name: 'TrdCollGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'TrdLeg',
        NotReqXML: 0,
        ComponentID: 2063,
        Name: 'TrdInstrmtLegGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'TrdSes',
        NotReqXML: 0,
        ComponentID: 2064,
        Name: 'TrdgSesGrp',
    },
    {
        CategoryID: 'CollateralManagement',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'UndColl',
        NotReqXML: 0,
        ComponentID: 2065,
        Name: 'UndInstrmtCollGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'OptimisedImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Undly',
        NotReqXML: 0,
        ComponentID: 2066,
        Name: 'UndInstrmtGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'TrdCapDt',
        NotReqXML: 0,
        ComponentID: 2069,
        Name: 'TrdCapDtGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Evnt',
        NotReqXML: 0,
        ComponentID: 2070,
        Name: 'EvntGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'AID',
        NotReqXML: 0,
        ComponentID: 2071,
        Name: 'SecAltIDGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'LegAID',
        NotReqXML: 0,
        ComponentID: 2072,
        Name: 'LegSecAltIDGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'UndAID',
        NotReqXML: 0,
        ComponentID: 2073,
        Name: 'UndSecAltIDGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Attrb',
        NotReqXML: 0,
        ComponentID: 2074,
        Name: 'AttrbGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'DlvInst',
        NotReqXML: 0,
        ComponentID: 2075,
        Name: 'DlvyInstGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        NotReqXML: 0,
        ComponentID: 2076,
        Name: 'SettlPtysSubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        NotReqXML: 0,
        ComponentID: 2077,
        Name: 'PtysSubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        NotReqXML: 0,
        ComponentID: 2078,
        Name: 'NstdPtysSubGrp',
    },
    {
        CategoryID: 'Session',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 95,
        AbbrName: 'Hop',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2085,
        Name: 'HopGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        NotReqXML: 0,
        ComponentID: 2079,
        Name: 'NstdPtys2SubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        NotReqXML: 0,
        ComponentID: 2080,
        Name: 'NstdPtys3SubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 95,
        AbbrName: 'StrtPrmGrp',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2086,
        Name: 'StrategyParametersGrp',
    },
    {
        CategoryID: 'SecuritiesReferenceData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'SecL',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2087,
        Name: 'SecLstUpdRelSymGrp',
    },
    {
        CategoryID: 'SecuritiesReferenceData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'SecLstUpdRelSymsLegGrp',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2088,
        Name: 'SecLstUpdRelSymsLegGrp',
    },
    {
        CategoryID: 'PositionMaintenance',
        ComponentType: 'BlockRepeating',
        Description:
            'The UnderlyingAmount component block is used to supply the underlying amounts, dates, settlement status and method for derivative positions.',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'UndDlvAmt',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 1026,
        Name: 'UnderlyingAmount',
    },
    {
        CategoryID: 'PositionMaintenance',
        ComponentType: 'BlockRepeating',
        Description: 'The ExpirationQty component block identified the expiration quantities and type of expiration.',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'Qty',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 1027,
        Name: 'ExpirationQty',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The use of this component block is restricted to instrument definition only and is not permitted to contain transactional information. Only a specified subset of party roles will be supported within the InstrumentParty block.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1032,
        Name: 'InstrumentParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2093,
        Name: 'InstrumentPtysSubGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'BlockRepeating',
        Description:
            'The SideTrdRegTS component block is used to convey regulatory timestamps associated with one side of a multi-sided trade event.',
        added: 'FIX.4.4',
        updatedEP: 97,
        AbbrName: 'TrdRegTS',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 1028,
        Name: 'SideTrdRegTS',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'RptSide',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2094,
        Name: 'TrdCapRptAckSideGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The use of this component block is restricted to instrument definition only and is not permitted to contain transactional information. Only a specified subset of party roles will be supported within the InstrumentParty block.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1033,
        Name: 'UndlyInstrumentParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2096,
        Name: 'UndlyInstrumentPtysSubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The DisplayInstruction component block is used to convey instructions on how a reserved order is to be handled in terms of when and how much of the order quantity is to be displayed to the market.',
        added: 'FIX.4.4',
        AbbrName: 'DsplyInstr',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1029,
        Name: 'DisplayInstruction',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The TriggeringInstruction component block specifies the conditions under which an order will be triggered by related market events as well as the behavior of the order in the market once it is triggered.',
        added: 'FIX.4.4',
        AbbrName: 'TrgrInstr',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1030,
        Name: 'TriggeringInstruction',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The RootParties component block is a version of the Parties component block used to provide root information regarding the owning and entering parties of a transaction.',
        added: 'FIX.4.4',
        AbbrName: 'Pty',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1031,
        Name: 'RootParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'Sub',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2097,
        Name: 'RootSubParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'TrdSessLstGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2099,
        Name: 'TrdSessLstGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.4.4',
        AbbrName: 'MsgTypeGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2098,
        Name: 'MsgTypeGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            "Ths SecurityTradingRules component block is used as part of security definition to specify the specific security's standard trading parameters such as trading session eligibility and other attributes of the security.",
        added: 'FIX.5.0',
        AbbrName: 'SecTrdgRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1058,
        Name: 'SecurityTradingRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'SettlDetails',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2139,
        Name: 'SettlDetails',
    },
    {
        CategoryID: 'SettlementInstruction',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'SettlObligInst',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2101,
        Name: 'SettlObligationInstructions',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'SecSizesGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2102,
        Name: 'SecSizesGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'StatsIndGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2103,
        Name: 'StatsIndGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'XMLDataBlock',
        Description:
            'The SecurityXML component is used for carrying security description or definition in an XML format. See "Specifying an FpML product specification from within the FIX Instrument Block" for more information on using this component block with FpML as a guideline.',
        added: 'FIX.5.0',
        AbbrName: 'SecXML',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1060,
        Name: 'SecurityXML',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'TickRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2118,
        Name: 'TickRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'StrkRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2119,
        Name: 'StrikeRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'MatRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2120,
        Name: 'MaturityRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'PxLmts2',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2121,
        Name: 'SecondaryPriceLimits',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'PxLmts',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2122,
        Name: 'PriceLimits',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'MDFeedTyps',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2123,
        Name: 'MarketDataFeedTypes',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'LotTypeRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2124,
        Name: 'LotTypeRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'MtchRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2125,
        Name: 'MatchRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'ExecInstRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2126,
        Name: 'ExecInstRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'TmInForceRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2127,
        Name: 'TimeInForceRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'OrdTypRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2128,
        Name: 'OrdTypeRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'TrdgSesRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2129,
        Name: 'TradingSessionRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'TrdgSesRulesGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2130,
        Name: 'TradingSessionRulesGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'BaseTrdgRules',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2131,
        Name: 'BaseTradingRules',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'MktSegGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2132,
        Name: 'MarketSegmentGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Sub',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2104,
        Name: 'DerivativeInstrumentPartySubIDsGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Pty',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2141,
        Name: 'DerivativeInstrumentParties',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Attrb',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2136,
        Name: 'DerivativeInstrumentAttribute',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Attrb',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2135,
        Name: 'NestedInstrumentAttribute',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'DerivInstrmt',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2140,
        Name: 'DerivativeInstrument',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'AID',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2105,
        Name: 'DerivativeSecurityAltIDGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Evnt',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2106,
        Name: 'DerivativeEventsGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'DerivSecDef',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2133,
        Name: 'DerivativeSecurityDefinition',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'RelSym',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2107,
        Name: 'RelSymDerivSecUpdGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'XMLDataBlock',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'SecXML',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1061,
        Name: 'DerivativeSecurityXML',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        updatedEP: 97,
        AbbrName: 'AID',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2108,
        Name: 'UnderlyingLegSecurityAltIDGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlock',
        Description: '',
        added: 'FIX.5.0',
        updatedEP: 97,
        AbbrName: 'Instrmt',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2134,
        Name: 'UnderlyingLegInstrument',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        updatedEP: 97,
        AbbrName: 'TradeCapLegUndlyGrp',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2109,
        Name: 'TradeCapLegUnderlyingsGrp',
    },
    {
        CategoryID: 'UserManagement',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'UserGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2137,
        Name: 'UsernameGrp',
    },
    {
        CategoryID: 'OrderMassHandling',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'NotAffectedOrdersGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2111,
        Name: 'NotAffectedOrdersGrp',
    },
    {
        CategoryID: 'SingleGeneralOrderHandling',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'FillsGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2112,
        Name: 'FillsGrp',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        updatedEP: 97,
        AbbrName: 'TrdRepIndicatorsGrp',
        addedEP: -1,
        NotReqXML: 0,
        updated: 'FIX.5.0SP1',
        ComponentID: 2113,
        Name: 'TrdRepIndicatorsGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'Block',
        Description:
            'The ApplicationSequenceControl is used for application sequencing and recovery. Consisting of ApplSeqNum (1181), ApplID (1180), ApplLastSeqNum (1350), and ApplResendFlag (1352), FIX application messages that carries this component block will be able to use application level sequencing. ApplID, ApplSeqNum and ApplLastSeqNum fields identify the application id, application sequence number and the previous application sequence number (in case of intentional gaps) on each application message that carries this block.',
        added: 'FIX.5.0',
        AbbrName: 'ApplSeqCtrl',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1057,
        Name: 'ApplicationSequenceControl',
    },
    {
        CategoryID: 'Application',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'ApplIDReqGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2115,
        Name: 'ApplIDRequestGrp',
    },
    {
        CategoryID: 'Application',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'ApplIDReqAckGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2116,
        Name: 'ApplIDRequestAckGrp',
    },
    {
        CategoryID: 'Application',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'ApplIDRptGrp',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2117,
        Name: 'ApplIDReportGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description: '',
        added: 'FIX.5.0',
        AbbrName: 'Sub',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 2142,
        Name: 'NstdPtys4SubGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        Description:
            'The NestedParties4 component block is identical to the Parties Block. It is used in other component blocks and repeating groups when nesting will take place resulting in multiple occurrences of the Parties block within a single FIX message. Use of NestedParties4 under these conditions avoids multiple references to the Parties block within the same message which is not allowed in FIX tag/value syntax.',
        added: 'FIX.5.0',
        AbbrName: 'Pty',
        addedEP: -1,
        NotReqXML: 0,
        ComponentID: 1059,
        Name: 'NestedParties4',
    },
    {
        CategoryID: 'TradeCapture',
        ComponentType: 'ImplicitBlock',
        added: 'FIX.5.0SP1',
        AbbrName: 'TrdRptOrdDetl',
        addedEP: 77,
        NotReqXML: 0,
        ComponentID: 2143,
        Name: 'TradeReportOrderDetail',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'RtSrc',
        addedEP: 82,
        NotReqXML: 0,
        ComponentID: 1062,
        Name: 'RateSource',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'BlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'TgtPty',
        addedEP: 85,
        NotReqXML: 0,
        ComponentID: 1063,
        Name: 'TargetParties',
    },
    {
        CategoryID: 'EventCommunication',
        ComponentType: 'ImplicitBlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'Refs',
        addedEP: 90,
        NotReqXML: 0,
        ComponentID: 2144,
        Name: 'NewsRefGrp',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description:
            'The ComplexEvent Group is a repeating block which allows an unlimited number and types of events in the lifetime of an option to be specified.',
        added: 'FIX.5.0SP1',
        AbbrName: 'CmplxEvnt',
        addedEP: 92,
        NotReqXML: 0,
        ComponentID: 2145,
        Name: 'ComplexEvents',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description:
            'The ComplexEventDate and ComplexEventTime components are used to constrain a complex event to a specific date range or time range. If specified the event is only effective on or within the specified dates and times.',
        added: 'FIX.5.0SP1',
        AbbrName: 'EvntDts',
        addedEP: 92,
        NotReqXML: 0,
        ComponentID: 2146,
        Name: 'ComplexEventDates',
    },
    {
        CategoryID: 'Common',
        ComponentType: 'ImplicitBlockRepeating',
        Description:
            'The ComplexEventTime component is nested within the ComplexEventDate in order to further qualify any dates placed on the event and is used to specify time ranges for which a complex event is effective. It is always provided within the context of start and end dates. The time range is assumed to be in effect for the entirety of the date or date range specified.',
        added: 'FIX.5.0SP1',
        AbbrName: 'EvntTms',
        addedEP: 92,
        NotReqXML: 0,
        ComponentID: 2147,
        Name: 'ComplexEventTimes',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'Reqs',
        addedEP: 93,
        NotReqXML: 0,
        ComponentID: 2148,
        Name: 'StrmAsgnReqGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'Rpts',
        addedEP: 93,
        NotReqXML: 0,
        ComponentID: 2149,
        Name: 'StrmAsgnRptGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'Instrmts',
        addedEP: 93,
        NotReqXML: 0,
        ComponentID: 2150,
        Name: 'StrmAsgnReqInstrmtGrp',
    },
    {
        CategoryID: 'MarketData',
        ComponentType: 'ImplicitBlockRepeating',
        added: 'FIX.5.0SP1',
        AbbrName: 'Instrmts',
        addedEP: 93,
        NotReqXML: 0,
        ComponentID: 2151,
        Name: 'StrmAsgnRptInstrmtGrp',
    },
];
