interface ISpecAbbreviations {
    Term: string;
    AbbrTerm: string;
    added: string;
    addedEP?: number;
    issue?: string;
}

export const ABBREVIATIONS: ISpecAbbreviations[] = [
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Acct',
        Term: 'Account',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Acrl',
        Term: 'Accrual',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Acrd',
        Term: 'Accrued',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ack',
        Term: 'Acknowledgement',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Actn',
        Term: 'Action',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Adj',
        Term: 'Adjust',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Adjmt',
        Term: 'Adjustment',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Adv',
        Term: 'Advertisement',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Afctd',
        addedEP: 41,
        Term: 'Affected',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Algo',
        addedEP: 42,
        Term: 'Algorithm',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Alloc',
        Term: 'Allocation',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'AOS',
        Term: 'AllowableOneSidedness',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Amt',
        Term: 'Amount',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Appl',
        addedEP: 63,
        Term: 'Application',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Asgn',
        Term: 'Assignment',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Attch',
        addedEP: 83,
        Term: 'Attachment',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Attrb',
        addedEP: 41,
        Term: 'Attribute',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Base',
        addedEP: 52,
        Term: 'Base',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Bhf',
        Term: 'Behalf',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Bnchmk',
        Term: 'Benchmark',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Bkng',
        Term: 'Booking',
    },
    {
        issue: 'SPEC-371',
        added: 'FIX.4.4',
        AbbrTerm: 'Brkr',
        Term: 'Broker',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Brkrs',
        Term: 'Brokers',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Biz',
        Term: 'Business',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Calc',
        Term: 'Calculation',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cxl',
        Term: 'Cancel',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cpcty',
        Term: 'Capacity',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Capt',
        Term: 'Capture',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Csh',
        Term: 'Cash',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Catgy',
        addedEP: 90,
        Term: 'Category',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cl',
        Term: 'Client',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cls',
        Term: 'Close',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cd',
        Term: 'Code',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Coll',
        Term: 'Collateral',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Comm',
        Term: 'Commission',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cmn',
        Term: 'Common',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Comp',
        Term: 'Company',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Cmplx',
        addedEP: 92,
        Term: 'Complex',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Cond',
        addedEP: 92,
        Term: 'Condition',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cnfm',
        Term: 'Confirmation',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Confirm',
        Term: 'Confirmation',
    },
    {
        issue: 'SPEC-371',
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Cntxt',
        addedEP: 96,
        Term: 'Context',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cntra',
        Term: 'Contra',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Ctrl',
        addedEP: 63,
        Term: 'Control',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Corp',
        Term: 'Corporate',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ctry',
        Term: 'Country',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cpn',
        Term: 'Coupon',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Crss',
        Term: 'Cross',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Cum',
        Term: 'Cumulative',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ccy',
        Term: 'Currency',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Crv',
        Term: 'Curve',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Data',
        Term: 'Data',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Db',
        Term: 'Database',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dt',
        Term: 'Date',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Def',
        Term: 'Definition',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Del',
        Term: 'Delete',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dlvr',
        Term: 'Deliver',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Deriv',
        addedEP: 52,
        Term: 'Derivative',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Desc',
        Term: 'Description',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dest',
        Term: 'Destination',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Detl',
        addedEP: 77,
        Term: 'Detail',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Dtrmn',
        addedEP: 92,
        Term: 'Determination',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dev',
        Term: 'Device',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Disc',
        Term: 'Discount',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dsctn',
        Term: 'Discretion',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dsctnry',
        Term: 'Discretionary',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'DK',
        Term: "Don't Know",
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Dup',
        Term: 'Duplicate',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Efctv',
        Term: 'Effective',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Enc',
        Term: 'Encoded',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Err',
        Term: 'Error',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Evnt',
        addedEP: 92,
        Term: 'Event',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Exch',
        Term: 'Exchange',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'EFP',
        Term: 'ExchangeForPhysical',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Exct',
        Term: 'Execute',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Exctn',
        Term: 'Execution',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Exr',
        Term: 'Exercise',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Fctr',
        Term: 'Factor',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Feed',
        addedEP: 42,
        Term: 'Feed',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'FX',
        Term: 'Foreign Currency',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Fwd',
        Term: 'Forward',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Force',
        addedEP: 52,
        Term: 'Force',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Fut',
        Term: 'Future',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'GTD',
        Term: 'Good Till Date',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Grp',
        Term: 'Group',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Hndl',
        Term: 'Handling',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'ID',
        Term: 'Identifier',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Implct',
        Term: 'Implicit',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Incr',
        addedEP: 22,
        Term: 'Increment',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ndx',
        Term: 'Index',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'IOI',
        Term: 'Indication of Interest',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ind',
        Term: 'Indicator',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Info',
        Term: 'Information',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Inpt',
        Term: 'Input',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Inq',
        Term: 'Inquiry',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Instn',
        Term: 'Institution',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Inst',
        addedEP: 44,
        Term: 'Instruction',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Instrmt',
        Term: 'Instrument',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Int',
        Term: 'Interest',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Iss',
        Term: 'Issue',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Issr',
        Term: 'Issuer',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Lang',
        addedEP: 90,
        Term: 'Language',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Lvl',
        Term: 'Level',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Lqdty',
        Term: 'Liquidity',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Lmt',
        addedEP: 52,
        Term: 'Limit',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'List',
        addedEP: 20,
        Term: 'List',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Loc',
        Term: 'Locate',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Lctn',
        Term: 'Location',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Lot',
        addedEP: 52,
        Term: 'Lot',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mnt',
        Term: 'Maintenance',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mgn',
        Term: 'Margin',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mkt',
        Term: 'Market',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Mass',
        addedEP: 58,
        Term: 'Mass',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mtch',
        Term: 'Match',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mat',
        Term: 'Maturity',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Max',
        Term: 'Maximum',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Msg',
        Term: 'Message',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Meth',
        addedEP: 52,
        Term: 'Method',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Min',
        Term: 'Minimum',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Misc',
        Term: 'Miscellaneous',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Model',
        addedEP: 59,
        Term: 'Model',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mod',
        Term: 'Modification',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mny',
        Term: 'Money',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mo',
        Term: 'Month',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mleg',
        Term: 'Multileg',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Mult',
        Term: 'Multiplier',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Nme',
        addedEP: 96,
        Term: 'Name',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Nst',
        Term: 'Nested',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ntwk',
        Term: 'Network',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'News',
        addedEP: 90,
        Term: 'News',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Notifctn',
        addedEP: 56,
        Term: 'Notification',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Notl',
        addedEP: 83,
        Term: 'Notional',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Num',
        Term: 'Number',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'No',
        Term: 'Number',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Oblig',
        addedEP: 44,
        Term: 'Obligation',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ofr',
        Term: 'Offer',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Oper',
        addedEP: 96,
        Term: 'Operator',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Opt',
        Term: 'Option',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ord',
        Term: 'Order',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Orig',
        Term: 'Original',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Oth',
        Term: 'Other',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Out',
        addedEP: 83,
        Term: 'Outstanding',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Prm',
        Term: 'Parameter',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pty',
        Term: 'Party',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pmt',
        Term: 'Payment',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pct',
        Term: 'Percent',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pctg',
        Term: 'Percentage',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Pltfm',
        addedEP: 96,
        Term: 'Platform',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Pnt',
        addedEP: 83,
        Term: 'Point',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pos',
        Term: 'Position',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Psbl',
        Term: 'Possible',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Prlm',
        Term: 'Preliminary',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Prcsn',
        addedEP: 92,
        Term: 'Precision',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Prev',
        Term: 'Previous',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Px',
        Term: 'Price',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pri',
        Term: 'Priority',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Prtztn',
        Term: 'Priotization',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Prod',
        Term: 'Product',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Pub',
        Term: 'Publish',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Qual',
        Term: 'Qualifier',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Qlty',
        Term: 'Quality',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Qty',
        Term: 'Quantity',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Quot',
        Term: 'Quote',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Rng',
        Term: 'Range',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rt',
        Term: 'Rate',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rtng',
        Term: 'Rating',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rsn',
        Term: 'Reason',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Red',
        Term: 'Redemption',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ref',
        Term: 'Reference',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rgst',
        Term: 'Registration',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rgstry',
        Term: 'Registry',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rej',
        Term: 'Reject',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Reltd',
        Term: 'Related',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Rltnshp',
        addedEP: 96,
        Term: 'Relationship',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rpt',
        Term: 'Report',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rpts',
        Term: 'Reports',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Repo',
        Term: 'Repurchase',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Req',
        Term: 'Request',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Reset',
        addedEP: 20,
        Term: 'Reset',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rsp',
        Term: 'Response',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rstmt',
        Term: 'Restatement',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rstct',
        Term: 'Restrict',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rstctn',
        Term: 'Restriction',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rstctns',
        Term: 'Restrictions',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Rstrct',
        addedEP: 83,
        Term: 'Restructuring',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rslt',
        Term: 'Result',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Risk',
        addedEP: 96,
        Term: 'Risk',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'R',
        Term: 'Roles',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Rnd',
        Term: 'Round',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Rules',
        addedEP: 52,
        Term: 'Rules',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Scope',
        addedEP: 96,
        Term: 'Scope',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: '2',
        Term: 'Secondary',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sec',
        Term: 'Security',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Seg',
        addedEP: 52,
        Term: 'Segment',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Snd',
        Term: 'Sender',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sndg',
        Term: 'Sending',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Snrty',
        addedEP: 83,
        Term: 'Seniority',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Seq',
        Term: 'Sequence',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Svc',
        Term: 'Service',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Ses',
        Term: 'Session',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Settl',
        Term: 'Settlement',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Shrt',
        Term: 'Short',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sz',
        Term: 'Size',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Src',
        Term: 'Source',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Stand',
        Term: 'Standing',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Start',
        addedEP: 52,
        Term: 'Start',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'St',
        Term: 'State',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Stat',
        Term: 'Status',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Stip',
        Term: 'Stipulation',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Strt',
        Term: 'Strategy',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Strm',
        addedEP: 93,
        Term: 'Stream',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Strk',
        Term: 'Strike',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sub',
        Term: 'Subscription',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Subsid',
        Term: 'Subsidiary',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sfx',
        Term: 'Suffix',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sym',
        Term: 'Symbol',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Sys',
        Term: 'System',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Tgt',
        Term: 'Target',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Trm',
        Term: 'Term',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Tick',
        addedEP: 52,
        Term: 'Tick',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Tkt',
        Term: 'Ticket',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Tm',
        Term: 'Time',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'TS',
        Term: 'Timestamp',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Tot',
        Term: 'Total',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Trkng',
        Term: 'Tracking',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Trd',
        Term: 'Trade',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Trdg',
        addedEP: 52,
        Term: 'Trading',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'TrdgSes',
        Term: 'TradingSession',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Txn',
        Term: 'Transaction',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Typ',
        Term: 'Type',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Und',
        Term: 'Underlying',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Upd',
        addedEP: 52,
        Term: 'Update',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Valu',
        Term: 'Value',
    },
    {
        added: 'FIX.5.0',
        AbbrTerm: 'Val',
        addedEP: 52,
        Term: 'Valuation',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Venu',
        addedEP: 77,
        Term: 'Venue',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Vol',
        Term: 'Volume',
    },
    {
        added: 'FIX.5.0SP1',
        AbbrTerm: 'Warn',
        addedEP: 96,
        Term: 'Warning',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Yr',
        Term: 'Year',
    },
    {
        added: 'FIX.4.4',
        AbbrTerm: 'Yld',
        Term: 'Yield',
    },
];
